home:
  path: /home
  controller: App\HomePageAction

api_login:
  path: /login/{community}
  controller: App\Auth\LoginAction

comment_add:
  path: /comment
  controller: App\Comments\AddComment
  methods: [ POST ]

feed_add:
  path: /feed
  controller: App\AddFeedItemAction
  methods: [ POST ]

activity_list:
  path: /activity
  controller: App\Activity\GetActivities
  methods: [ GET ]

activity_last:
  path: /activity/last
  controller: App\Activity\GetLastActivity
  methods: [ GET ]

activity_add:
  path: /activity/add
  controller: App\Activity\AddActivity
  methods: [ POST ]

activity_moderate:
  path: /activity/moderation
  controller: App\Activity\ModerateActivity
  methods: [ POST ]

activity_validate:
  path: /activity/validate
  controller: App\Activity\ValidateActivity
  methods: [ GET ]

activity_get_for_moderation:
  path: /activity/moderation
  controller: \App\Activity\GetActivityForModeration
  methods: [ GET ]

activity_update_location:
  path: /activity/location
  controller: App\Activity\UpdateActivityLocation
  methods: [ POST ]

get_user:
  path: /user
  controller: App\User\GetUser
  methods: [ GET ]

register_user:
  path: /auth/user
  controller: App\User\RegisterUser
  methods: [ POST ]

update_user:
  path: /user
  controller: App\User\UpdateUser
  methods: [ PATCH ]

register_admin:
  path: /auth/admin
  controller: App\User\RegisterUser
  methods: [ POST ]

get_communites:
  path: /communities
  controller: App\Community\GetCommunities
  methods: [ GET ]

add_message:
  path: /violation
  controller: App\AddMessage
  methods: [ POST ]
