home:
  path: /home
  controller: App\HomePageAction

api_login:
  path: /login
  controller: App\Auth\LoginAction

comment_add:
  path: /comment
  controller: App\Comments\AddComment
  methods: [ POST ]

comment_archive:
  path: /comment/{id}
  controller: App\Comments\ArchiveComment
  methods: [ DELETE ]

comment_list:
  path: /comment/{type}/{id}
  controller: App\Comments\GetCommentsAction
  methods: [ GET ]

feed_add:
  path: /feed
  controller: App\AddFeedItemAction
  methods: [ POST ]

rate:
  path: /rate/{type}/{entity}/{id}
  controller: App\Rating\RateAction
  methods: [ POST ]

unrate:
  path: /unrate/{entity}/{id}
  controller: App\Rating\UnrateAction
  methods: [ POST ]

activity_list:
  path: /activity
  controller: App\Activity\GetActivities
  methods: [ GET ]

activity_last:
  path: /activity/last
  controller: App\Activity\GetLastActivity
  methods: [ GET ]

activity_add:
  path: /activity/add
  controller: App\Activity\AddActivity
  methods: [ POST ]

activity_moderate:
  path: /activity/moderation
  controller: App\Activity\ModerateActivity
  methods: [ POST ]

activity_validate:
  path: /activity/validate
  controller: App\Activity\ValidateActivity
  methods: [ GET ]

activity_get_for_moderation:
  path: /activity/moderation
  controller: \App\Activity\GetActivityForModeration
  methods: [ GET ]

activity_update_location:
  path: /activity/location
  controller: App\Activity\UpdateActivityLocation
  methods: [ POST ]

get_user:
  path: /user
  controller: App\User\GetUser
  methods: [ GET ]

register_user:
  path: /auth/user
  controller: App\User\RegisterUser
  methods: [ POST ]

update_user:
  path: /user
  controller: App\User\UpdateUser
  methods: [ PATCH ]

register_admin:
  path: /auth/admin
  controller: App\User\RegisterUser
  methods: [ POST ]

activity_comments:
  path: /comments
  controller: App\Comments\GetListAction

get_communites:
  path: /communities
  controller: App\Community\GetCommunities
  methods: [ GET ]

person_upvote:
  path: /person/upvote
  controller: App\Rating\UpvotePerson
  methods: [ POST ]

person_downvote:
  path: /person/downvote
  controller: App\Rating\DownvotePerson
  methods: [ POST ]

person_unrate:
  path: /person/unrate
  controller: App\Rating\UnratePerson
  methods: [ POST ]

add_message:
  path: /violation
  controller: App\AddMessage
  methods: [ POST ]
