widget:
    path: /private/widget
    controller: App\DisplayWidget

index:
    path: /
    controller: App\DisplayWidget

api_login:
    path: /login
    controller: App\LoginAction

add_comment:
    path: /comment
    controller: App\AddComment
    methods: [POST]
