widget:
    path: /private/widget
    controller: App\DisplayWidget

index:
    path: /
    controller: App\DisplayWidget

api_login:
    path: /login
    controller: App\Auth\LoginAction

add_comment:
    path: /comment
    controller: App\AddComment
    methods: [POST]

ad_add:
    path: /ad
    controller: App\Ad\AddAdAction
    methods: [POST, OPTIONS]

ad_list:
    path: /ad
    controller: App\Ad\GetListAction
    methods: [GET]
