widget:
    path: /private/widget
    controller: App\DisplayWidget

index:
    path: /
    controller: App\DisplayWidget

home:
    path: /home
    controller: App\HomePageAction

api_login:
    path: /login
    controller: App\Auth\LoginAction

add_comment:
    path: /comment
    controller: App\AddComment
    methods: [POST]

comment_list:
    path: /comment/{type}/{id}
    controller: App\GetCommentsAction
    methods: [GET]

ad_add:
    path: /ad
    controller: App\Ad\AddAdAction
    methods: [POST, OPTIONS]

ad_list:
    path: /ad
    controller: App\Ad\GetAdsAction
    methods: [GET]

ad_get:
    path: /ad/{id}
    controller: App\Ad\GetAdAction
    methods: [GET]

place_get:
    path: /place/{id}
    controller: App\Place\GetPlaceAction
    methods: [GET]

person_list:
    path: /person
    controller: App\Person\GetPeopleAction
    methods: [GET]

person_get:
    path: /person/{id}
    controller: App\Person\GetPersonAction
    methods: [GET]

event_list:
    path: /event
    controller: App\Event\GetEventsAction
    methods: [GET]

event_get:
    path: /event/{id}
    controller: App\Event\GetEventAction
    methods: [GET]

feed:
    path: /feed
    controller: App\GetFeedAction
    methods: [GET]

organization_list:
    path: /organization
    controller: App\Organization\GetOrganizationsAction
    methods: [GET]

organization_get:
    path: /organization/{id}
    controller: App\Organization\GetOrganizationAction
    methods: [GET]
