# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  private_key: '%env(resolve:JWT_SECRET_KEY)%'
  loshitsaToken: "%env(loshitsa_BOT_TOKEN)%"
  vitebskToken: "%env(vitebsk_BOT_TOKEN)%"
  bntuToken: "%env(bntu_BOT_TOKEN)%"
services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $slug: '%env(SLUG)%'
      $domain: "%env(DOMAIN)%"
      $allowedGroups: "%env(json:GROUPS)%"
      $s3Key: "%env(AWS_KEY)%"
      $s3Secret: "%env(AWS_SECRET)%"
      $s3Bucket: "%env(S3_BUCKET)%"
      $privateKey: '%private_key%'
      $publicKey: '%env(resolve:PUBLIC_KEY)%'
      $jwtPublicKey: '%env(resolve:JWT_PUBLIC_KEY)%'

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  App\DisplayWidget:
    tags: [ 'controller.service_arguments' ]

  App\HomePageAction:
    tags: [ 'controller.service_arguments' ]

  App\ErrorListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  App\Auth\GetUser:
    tags:
      - { name: controller.argument_value_resolver, priority: 101 }

  App\TelegramAdapter:
    public: true

  App\S3Uploader: ~

  App\FileUploader: '@App\S3Uploader'

  App\BotTokenFactory: ~
