version: '3.4'

services:
  nginx:
    image: nginx:1.19-alpine
    ports:
      - "9030:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./../:/app:ro
    networks:
      - backend

  php:
    build:
      context: './../'
      dockerfile: 'infrastructure/php/Dockerfile'
    networks:
      - backend
    user: ${HOST_UID}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=symfony-life
    command: ["php-fpm", "--allow-to-run-as-root", "-d", "zend_extension=xdebug.so"]
    volumes:
      - "../.:/app"

networks:
  backend:
    driver: bridge
